// varied 'Armour' visual effects 
// IWD style Cause Wounds spells - check for SR before installing
//


PRINT ~Installing individualised armour effects...~


ACTION_FOR_EACH item IN ~1WDGARMR.VVC~ ~1WDSARMR.VVC~ ~GARMORH.BAM~ ~SARMORH.BAM~ BEGIN
COPY		~1pp/item/spells_and_scrolls/tweak/%item%~ ~override~
END


    ACTION_IF (FILE_EXISTS_IN_GAME ~SPWI317.SPL~) THEN BEGIN
      COPY_EXISTING ~SPWI317.SPL~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x6a "fx_off"
    READ_SHORT 0x6e "fx_idx"
    READ_SHORT 0x70 "fx_num"

    PATCH_IF (fx_off > 0x71) BEGIN
      FOR (index = fx_idx ; index < fx_num ; index = index + 1) BEGIN
        READ_SHORT ("%fx_off%" +        ("%index%" * 0x30)) "opcode"
        READ_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) "resref"
        PATCH_IF (("%opcode%" = 215) AND ("%resref%" STRING_EQUAL_CASE "ICARMOR"))  BEGIN
          WRITE_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) ~1WDGARMR~ #8
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
  END

 ACTION_IF (FILE_EXISTS_IN_GAME ~SPWI414.SPL~) THEN BEGIN
      COPY_EXISTING ~SPWI414.SPL~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x6a "fx_off"
    READ_SHORT 0x6e "fx_idx"
    READ_SHORT 0x70 "fx_num"

    PATCH_IF (fx_off > 0x71) BEGIN
      FOR (index = fx_idx ; index < fx_num ; index = index + 1) BEGIN
        READ_SHORT ("%fx_off%" +        ("%index%" * 0x30)) "opcode"
        READ_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) "resref"
        PATCH_IF (("%opcode%" = 215) AND ("%resref%" STRING_EQUAL_CASE "SPSARMOR"))  BEGIN
          WRITE_ASCII ("%fx_off%" + 0x14 + ("%index%" * 0x30)) ~1WDSARMR~ #8
        END
      END
    END
  END
  BUT_ONLY_IF_IT_CHANGES
  END

ACTION_IF (FILE_EXISTS_IN_GAME ~dvsrv3.mrk~) THEN BEGIN
  PRINT ~Skipping PnP/IWD-style 'cause wound" spells due to Spell Revisions V3/V4 being installed...~
  
  ACTION_FOR_EACH item IN ~1WDCCDAM.BAM~ ~1WDCCDAM.VVC~ ~1WDCLDAM.BAM~ ~1WDCLDAM.VVC~ ~1WDCMDAM.BAM~ ~1WDCMDAM.VVC~ ~1WDCSDAM.BAM~ ~1WDCSDAM.VVC~ BEGIN
  COPY		~1pp/item/spells_and_scrolls/tweak/%item%~ ~override~
  END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR119D.spl~) BEGIN
  COPY_EXISTING ~DVPR119D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR219D.spl~) BEGIN
  COPY_EXISTING ~DVPR219D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR321D.spl~) BEGIN
  COPY_EXISTING ~DVPR321D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR414D.spl~) BEGIN
  COPY_EXISTING ~DVPR414D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

ACTION_IF (FILE_EXISTS_IN_GAME ~DVPR510D.spl~) BEGIN
  COPY_EXISTING ~DVPR510D.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    REPLACE_TEXTUALLY CASE_INSENSITIVE ~ICMAGICH~ ~1WDCMDAM~
  END
  BUT_ONLY_IF_IT_CHANGES
END

PRINT ~Do you want existing 'cause wound' spells to use IWD-style icons? (healing icon in red) 

1. Yes please.
2. No, keep BG2 icons for existing spells.

PLEASE ENTER  1 OR 2  ~
ACTION_READLN how
OUTER_WHILE NOT(IS_AN_INT %how%) || (%how% > 2) || (%how% < 1) BEGIN
 PRINT ~Do you want existing 'cause wound' spells to use IWD-style icons? (healing icon in red) 

1. Yes please.
2. No, keep BG2 icons for existing spells.

PLEASE ENTER  1 OR 2  ~
 ACTION_READLN how
END

ACTION_IF (%how% = 1) THEN BEGIN
PRINT ~Copying...~
COPY		~1pp/item/spells_and_scrolls/tweak/1WDCLWA.bam~ ~override/SPPR119A.bam~
COPY		~1pp/item/spells_and_scrolls/tweak/1WDCLWB.bam~ ~override/SPPR119B.bam~
COPY		~1pp/item/spells_and_scrolls/tweak/1WDCLWC.bam~ ~override/SPPR119C.bam~

COPY		~1pp/item/spells_and_scrolls/tweak/1WDCMWA.bam~ ~override/SPPR219A.bam~
COPY		~1pp/item/spells_and_scrolls/tweak/1WDCMWB.bam~ ~override/SPPR219B.bam~
COPY		~1pp/item/spells_and_scrolls/tweak/1WDCMWC.bam~ ~override/SPPR219C.bam~

ACTION_FOR_EACH item IN ~SPPR414A.bam~ ~SPPR414B.bam~ ~SPPR414C.bam~ ~SPPR510A.bam~ ~SPPR510B.bam~ ~SPPR510C.bam~ BEGIN
  COPY		~1pp/item/spells_and_scrolls/tweak/%item%~ ~override~
  END
END
  
END ELSE BEGIN

PRINT ~Installing PnP/IWD-style 'cause wounds' spells...~

ACTION_FOR_EACH item IN ~1WDCCDAM.BAM~ ~1WDCCDAM.VVC~ ~1WDCLDAM.BAM~ ~1WDCLDAM.VVC~ ~1WDCLWA.bam~ ~1WDCLWB.bam~ ~1WDCLWC.bam~ ~1WDCMDAM.BAM~ ~1WDCMDAM.VVC~ ~1WDCMWA.bam~ ~1WDCMWB.bam~ ~1WDCMWC.bam~ ~1WDCSDAM.BAM~ ~1WDCSDAM.VVC~ BEGIN
COPY		~1pp/item/spells_and_scrolls/tweak/%item%~ ~override~
END



PRINT ~Do you want existing 'cause wound' spells to use IWD-style icons? (healing icon in red) 

1. Yes please.
2. No, keep BG2 icons for existing spells.

PLEASE ENTER  1 OR 2  ~
ACTION_READLN how
OUTER_WHILE NOT(IS_AN_INT %how%) || (%how% > 2) || (%how% < 1) BEGIN
 PRINT ~Do you want existing 'cause wound' spells to use IWD-style icons? (healing icon in red) 

1. Yes please.
2. No, keep BG2 icons for existing spells.

PLEASE ENTER  1 OR 2  ~
 ACTION_READLN how
END

ACTION_IF (%how% = 1) THEN BEGIN
PRINT ~Copying...~
ACTION_FOR_EACH item IN ~SPPR414A.bam~ ~SPPR414B.bam~ ~SPPR414C.bam~ ~SPPR510A.bam~ ~SPPR510B.bam~ ~SPPR510C.bam~ BEGIN
COPY		~1pp/item/spells_and_scrolls/tweak/%item%~ ~override~
END
 END


 
ACTION_FOR_EACH ~spell~ IN ~SPPR414~ ~SPPR510~ ~SPPR608~ BEGIN

 OUTER_SET uname = 0
 
    ACTION_IF (FILE_EXISTS_IN_GAME ~%spell%.spl~) THEN BEGIN
COPY_EXISTING ~%spell%.spl~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_LONG  0x8 uname
      END
	  
COPY ~1pp/item/spells_and_scrolls/tweak/%spell%.spl~ ~override~
 PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    WRITE_LONG  0x8 uname
      END
	  
  END 
 
 END
 
 
 ACTION_IF (FILE_EXISTS_IN_GAME ~SPPR414.SPL~) THEN BEGIN
COPY_EXISTING ~SPPR414.SPL~ ~override~
  SAY 0x50 ~Cause Serious Wounds (Necromancy) 
Level: 4
Sphere: Healing 
Range: Touch 
Duration: Permanent 
Casting Time: 7 
Area of Effect: Creature touched 
Saving Throw: 1/2 

This spell is the reverse of cure serious wounds.  Instead of healing the creature touched, it causes damage.  On a successful touch from the priest, the spell inflicts 17 damage upon the target.  A successful saving throw against spells halves the damage.~
      END
	  

 ACTION_IF (FILE_EXISTS_IN_GAME ~SPPR510.SPL~) THEN BEGIN
COPY_EXISTING ~SPPR510.SPL~ ~override~
  SAY 0x50 ~Cause Critical Wounds (Necromancy) 
Level: 5
Sphere: Healing 
Range: Touch 
Duration: Permanent 
Casting Time: 8
Area of Effect: Creature touched 
Saving Throw: 1/2

This spell is the reverse of cure critical wounds.  Instead of healing the creature touched, it causes damage.  On a successful touch from the priest, the spell inflicts 27 damage upon the target.  A successful saving throw against spells halves the damage.~
      END
	  
	  
 ACTION_IF (FILE_EXISTS_IN_GAME ~SPPR608.SPL~) THEN BEGIN
COPY_EXISTING ~SPPR608.SPL~ ~override~
  SAY 0x50 ~Harm (Necromancy) 
Level: 6
Sphere: Healing 
Range: Touch 
Duration: Permanent 
Casting Time: 1 round
Area of Effect: Creature touched 
Saving Throw: Special 

This spell is the reverse of Heal.  Instead of healing the creature touched, it causes damage.  On a successful touch from the priest, the target will suffer 1d6 points of damage per level of the caster, up to a maximum of 15d6 points of damage at 15th level. If the target fails its saving throw, its remaining hit points will be reduced to 1.~
      END
	  
	
 ACTION_IF (FILE_EXISTS_IN_GAME ~SPPR142.SPL~ OR FILE_EXISTS_IN_GAME ~SPPR342.SPL~) THEN BEGIN	
PRINT ~WARNING: SPPR142/342 seem to be already taken by a previously installed mod. Proceeding to install may cause issues. 

1. I understand and want to continue.
2. Cancel installation.

PLEASE ENTER  1 OR 2  ~
ACTION_READLN how
OUTER_WHILE NOT(IS_AN_INT %how%) || (%how% > 2) || (%how% < 1) BEGIN
 PRINT ~WARNING: SPPR142/342 seem to be already taken by a previously installed mod. Proceeding to install may cause issues. 

1. I understand and want to continue.
2. Cancel installation.

PLEASE ENTER  1 OR 2  ~
 ACTION_READLN how
END

ACTION_IF (%how% = 2) THEN BEGIN
FAIL ~Aborted.~
END
	END  
	  
	  
ADD_SPELL ~1pp/item/spells_and_scrolls/tweak/SPPR142.SPL~ 1 1 ~CLERIC_CAUSE_LIGHT_WOUNDS~
// COPY ~1pp/item/spells_and_scrolls/tweak/SPPR142.SPL~ ~override~
SAY 0x8 ~Cause Light Wounds~
SAY 0x50 ~Cause Light Wounds (Necromancy) 
Level: 1
Sphere: Healing 
Range: Touch 
Duration: Permanent 
Casting Time: 5 
Area of Effect: Creature touched 
Saving Throw: 1/2 

This spell is the reverse of cure light wounds.  Instead of healing the creature touched, it causes damage.  On a successful touch from the priest, the spell inflicts 8 damage upon the target.  A successful saving throw against spells halves the damage.~


ADD_SPELL ~1pp/item/spells_and_scrolls/tweak/SPPR342.SPL~ 1 3 ~CLERIC_CAUSE_MEDIUM_WOUNDS~
//COPY ~1pp/item/spells_and_scrolls/tweak/SPPR342.SPL~ ~override~
SAY 0x8 ~Cause Medium Wounds~
SAY 0x50 ~Cause Medium Wounds (Necromancy) 
Level: 3
Sphere: Healing 
Range: Touch 
Duration: Permanent 
Casting Time: 5 
Area of Effect: Creature touched 
Saving Throw: 1/2 

This spell is the reverse of cure medium wounds.  Instead of healing the creature touched, it causes damage.  On a successful touch from the priest, the spell inflicts 13 damage upon the target.  A successful saving throw against spells halves the damage.~

END // SR check