// Colourable Quarterstaves, 1pp beta
// Presented in Technicolour

PRINT ~Installing Colourable Quarterstaves core ~

PRINT ~Copying...~

COPY ~1pp/additions/obj_anim/QS/WQLQSA2.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQLQSA4.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQLQSA6.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQLQSG1.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQMQSA2.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQMQSA4.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQMQSA6.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQMQSG1.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQNQSA2.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQNQSA4.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQNQSA6.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQNQSG1.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQSQSA2.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQSQSA4.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQSQSA6.BAM~ ~override~
COPY ~1pp/additions/obj_anim/QS/WQSQSG1.BAM~ ~override~

ACTION_IF (GAME_IS ~totlm how bg2 tob tutu tutu_totsc ca~) BEGIN
COPY ~1pp/additions/obj_1pp/WPLQSINV.bam~ ~override~
COPY ~1pp/additions/obj_1pp/WPMQSINV.bam~ ~override~
COPY ~1pp/additions/obj_1pp/WPNQSINV.bam~ ~override~
COPY ~1pp/additions/obj_1pp/WPSQSINV.bam~ ~override~
END

PRINT ~Installing core item patches~

LAUNCH_ACTION_MACRO ~Locations~

PRINT ~Patching...~

ACTION_IF (FILE_EXISTS_IN_GAME ~enstaff.itm~) THEN BEGIN
COPY_EXISTING ~enstaff.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 109		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~hgnya01.itm~) THEN BEGIN
COPY_EXISTING ~hgnya01.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 23		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 36		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 23		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~hgwra01.itm~) THEN BEGIN
COPY_EXISTING ~hgwra01.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET setr = 0x60 // Set Red
SET setg = 0x00 // Set Green
SET setb = 0x71 // Set Blue
SET speed = 0x1E // Speed
SET location = wgrey
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x00 // Set Red
SET setg = 0x00 // Set Green
SET setb = 0xC0 // Set Blue
SET speed = 0x14 // Speed
SET location = wteal
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x63 // Set Red
SET setg = 0x63 // Set Green
SET setb = 0xE6 // Set Blue
SET speed = 0x0C // Speed
SET location = wpink
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x6D // Set Red
SET setg = 0x6D // Set Green
SET setb = 0xFF // Set Blue
SET speed = 0x0C // Speed
SET location = wblue
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x60 // Set Red
SET setg = 0x00 // Set Green
SET setb = 0x71 // Set Blue
SET speed = 0x1E // Speed
SET location = wred
LAUNCH_PATCH_MACRO ~pulse~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~misc5t.itm~) THEN BEGIN
COPY_EXISTING ~misc5t.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 94		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 238		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 238		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 99		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~misc9o.itm~) THEN BEGIN
COPY_EXISTING ~misc9o.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~rods04.itm~) THEN BEGIN
COPY_EXISTING ~rods04.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 102		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 91		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 102		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~rods05.itm~) THEN BEGIN
COPY_EXISTING ~rods05.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 5		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 6		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 5		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 3		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~sahstaff.itm~) THEN BEGIN
COPY_EXISTING ~sahstaff.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

// ordinary staves

ACTION_IF (FILE_EXISTS_IN_GAME ~staf01.itm~) THEN BEGIN
COPY_EXISTING ~staf01.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_staf01.itm~) THEN BEGIN
COPY_EXISTING ~_staf01.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END


ACTION_IF (FILE_EXISTS_IN_GAME ~staf02.itm~) THEN BEGIN
COPY_EXISTING ~staf02.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 5		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END


ACTION_IF (FILE_EXISTS_IN_GAME ~_staf02.itm~) THEN BEGIN
COPY_EXISTING ~_staf02.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 5		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf03.itm~) THEN BEGIN
COPY_EXISTING ~staf03.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf04.itm~) THEN BEGIN
COPY_EXISTING ~staf04.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_staf04.itm~) THEN BEGIN
COPY_EXISTING ~_staf04.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 24		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 90		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf05.itm~) THEN BEGIN
COPY_EXISTING ~staf05.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 109		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~_staf05.itm~) THEN BEGIN
COPY_EXISTING ~_staf05.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 109		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf08.itm~) THEN BEGIN
COPY_EXISTING ~staf08.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 81		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 66		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 83		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 85		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 85		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x00 // Set Red
SET setg = 0x14 // Set Green
SET setb = 0x14 // Set Blue
SET location = wgrey
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x19 // Set Green
SET setb = 0x19 // Set Blue
SET location = wteal
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x28 // Set Green
SET setb = 0x28 // Set Blue
SET location = wpink
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x1E // Set Green
SET setb = 0x1E // Set Blue
SET location = wblue
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x28 // Set Green
SET setb = 0x28 // Set Blue
SET location = wred
LAUNCH_PATCH_MACRO ~glow~
END
END


ACTION_IF (FILE_EXISTS_IN_GAME ~_staf08.itm~) THEN BEGIN
COPY_EXISTING ~_staf08.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 81		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 66		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 83		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 85		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 85		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x00 // Set Red
SET setg = 0x14 // Set Green
SET setb = 0x14 // Set Blue
SET location = wgrey
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x19 // Set Green
SET setb = 0x19 // Set Blue
SET location = wteal
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x28 // Set Green
SET setb = 0x28 // Set Blue
SET location = wpink
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x1E // Set Green
SET setb = 0x1E // Set Blue
SET location = wblue
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x28 // Set Green
SET setb = 0x28 // Set Blue
SET location = wred
LAUNCH_PATCH_MACRO ~glow~
END
END


ACTION_IF (FILE_EXISTS_IN_GAME ~staf09.itm~) THEN BEGIN
COPY_EXISTING ~staf09.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 14		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 13		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 10		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf10.itm~) THEN BEGIN
COPY_EXISTING ~staf10.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 96		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 100		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 102		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf11.itm~) THEN BEGIN
COPY_EXISTING ~staf11.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
SET opcode_to_delete = 7
LAUNCH_PATCH_MACRO DELETE_ITEM_EQEFFECT
SET opcode_to_delete = 8
LAUNCH_PATCH_MACRO DELETE_ITEM_EQEFFECT
SET gradient = 112		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 113		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 93		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 98		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf12.itm~) THEN BEGIN
COPY_EXISTING ~staf12.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 17		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 21		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 94		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 5		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf13.itm~) THEN BEGIN
COPY_EXISTING ~staf13.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 18		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 100		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 101		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 104		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0xC6 // Set Red
SET setg = 0xD5 // Set Green
SET setb = 0xDE // Set Blue
SET speed = 0x14 // Speed
SET location = wteal
LAUNCH_PATCH_MACRO ~pulse~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf14.itm~) THEN BEGIN
COPY_EXISTING ~staf14.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 234		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 91		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 234		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 94		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 91		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf15.itm~) THEN BEGIN
COPY_EXISTING ~staf15.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 14		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 17		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 28		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf16.itm~) THEN BEGIN
COPY_EXISTING ~staf16.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 38		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 20		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 39		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 38		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 39		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf17.itm~) THEN BEGIN
COPY_EXISTING ~staf17.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 10		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 11		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 111		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 12		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 10		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf18.itm~) THEN BEGIN
COPY_EXISTING ~staf18.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 66		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 81		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 43		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 39		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf19.itm~) THEN BEGIN
COPY_EXISTING ~staf19.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 105		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wgrey
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x77 // Set Green
SET setb = 0xB6 // Set Blue
SET location = wteal
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x90 // Set Green
SET setb = 0xD0 // Set Blue
SET location = wpink
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wblue
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wred
LAUNCH_PATCH_MACRO ~glow~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf20.itm~) THEN BEGIN
COPY_EXISTING ~staf20.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 97		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 96		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 97		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wgrey
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x77 // Set Green
SET setb = 0xB6 // Set Blue
SET location = wteal
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x90 // Set Green
SET setb = 0xD0 // Set Blue
SET location = wpink
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wblue
LAUNCH_PATCH_MACRO ~glow~
SET setr = 0x00 // Set Red
SET setg = 0x8B // Set Green
SET setb = 0xCA // Set Blue
SET location = wred
LAUNCH_PATCH_MACRO ~glow~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf21.itm~) THEN BEGIN
COPY_EXISTING ~staf21.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 42		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 37		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 36		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 42		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 36		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf22.itm~) THEN BEGIN
COPY_EXISTING ~staf22.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 42		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 37		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 36		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 42		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 36		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf23.itm~) THEN BEGIN
COPY_EXISTING ~staf23.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 208		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 138		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 208		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 1		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 138		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x21 // Set Red
SET setg = 0xC0 // Set Green
SET setb = 0x00 // Set Blue
SET speed = 0x28 // Speed
SET location = wgrey
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x37 // Set Red
SET setg = 0xA6 // Set Green
SET setb = 0x00 // Set Blue
SET speed = 0x28 // Speed
SET location = wteal
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x21 // Set Red
SET setg = 0xD2 // Set Green
SET setb = 0x00 // Set Blue
SET speed = 0x28 // Speed
SET location = wpink
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x21 // Set Red
SET setg = 0xC0 // Set Green
SET setb = 0x00 // Set Blue
SET speed = 0x28 // Speed
SET location = wblue
LAUNCH_PATCH_MACRO ~pulse~
SET setr = 0x21 // Set Red
SET setg = 0xC0 // Set Green
SET setb = 0x00 // Set Blue
SET speed = 0x28 // Speed
SET location = wred
LAUNCH_PATCH_MACRO ~pulse~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~staf24.itm~) THEN BEGIN
COPY_EXISTING ~staf24.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 25		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 66		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 81		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 43		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 39		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~wastaff.itm~) THEN BEGIN
COPY_EXISTING ~wastaff.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 10		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 15		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 10		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 10		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
SET setr = 0x4C // Set Red
SET setg = 0xFF // Set Green
SET setb = 0x00 // Set Blue
SET location = wteal
LAUNCH_PATCH_MACRO ~glow~
END
END


PRINT ~Installing mod item patches (if found)~

PRINT ~Patching...~

LAUNCH_ACTION_MACRO ~Locations~

PRINT ~Patching...~

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st1.itm~) THEN BEGIN
COPY_EXISTING ~bw02st1.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 81		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 15		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st2.itm~) THEN BEGIN
COPY_EXISTING ~bw02st2.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 26		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st3.itm~) THEN BEGIN
COPY_EXISTING ~bw02st3.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 81		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 15		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st4.itm~) THEN BEGIN
COPY_EXISTING ~bw02st4.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 26		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st5.itm~) THEN BEGIN
COPY_EXISTING ~bw02st5.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 81		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 15		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 25		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 27		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~bw02st6.itm~) THEN BEGIN
COPY_EXISTING ~bw02st6.itm~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN 
LAUNCH_PATCH_MACRO ~clear~
SET gradient = 26		// colour index
SET location = wgrey		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wteal		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 19		// colour index
SET location = wpink		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 24		// colour index
SET location = wblue		// location
LAUNCH_PATCH_MACRO ~colour~
SET gradient = 22		// colour index
SET location = wred		// location * compatibility 
LAUNCH_PATCH_MACRO ~colour~
END
END